version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - cicd-network

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - cicd-network

  sonarqube:
    image: sonarqube:7.9-community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    networks:
      - cicd-network

volumes:
  jenkins-data:
  nexus-data:
  sonarqube-data:

networks:
  cicd-network:
